// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using ReelVault.Api;

#nullable disable

namespace ReelVault.Api.Migrations
{
    [DbContext(typeof(ReelVaultDbContext))]
    [Migration("20260725182742_AddEnrichment")]
    partial class AddEnrichment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReelVault.Api.Items.SavedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Area")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EnrichedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnrichmentData")
                        .HasColumnType("jsonb");

                    b.Property<string>("EnrichmentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("NotEnriched");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RawModelOutput")
                        .HasColumnType("text");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasComputedColumnSql("to_tsvector('english',\n    coalesce(\"Title\", '') || ' ' ||\n    coalesce(\"Summary\", '') || ' ' ||\n    coalesce(\"Area\", '') || ' ' ||\n    coalesce(\"City\", '') || ' ' ||\n    coalesce(\"CategoryData\" ->> 'Name', '') || ' ' ||\n    coalesce(\"CategoryData\" ->> 'PlaceName', '') || ' ' ||\n    coalesce(\"CategoryData\" ->> 'Cuisine', '') || ' ' ||\n    coalesce(\"CategoryData\" ->> 'PlaceType', '') || ' ' ||\n    coalesce(\"CategoryData\" ->> 'MustTry', '') || ' ' ||\n    coalesce(\"CategoryData\" ->> 'Highlights', '')\n)", true);

                    b.Property<string>("SourceCaption")
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserNotes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Area");

                    b.HasIndex("Category");

                    b.HasIndex("City");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SavedAt");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.ToTable("SavedItems");
                });

            modelBuilder.Entity("ReelVault.Shared.HealthCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("HealthChecks");
                });
#pragma warning restore 612, 618
        }
    }
}
